### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gha241** [schwarper/cs2-tags#13]
09:01:03 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Runtime.InteropServices.COMException (0x80131130): Unable to get nested type properties.
   at Tags.Player.GetTag(CCSPlayerController player)
   at Tags.Tags.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in C:\Users\mervt\OneDrive\Masaüstü\tags\cs2-tags\cs2-tags\src\cs2-tag.cs:line 62
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by schwarper** [comment]
> 09:01:03 [EROR] (cssharp:Core) Error invoking callback System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException (0x80131130): Unable to get nested type properties. at Tags.Player.GetTag(CCSPlayerController player) at Tags.Tags.OnPlayerConnect(EventPlayerConnectFull event, GameEventInfo info) in C:\Users\mervt\OneDrive\Masaüstü\tags\cs2-tags\cs2-tags\src\cs2-tag.cs:line 62 at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1) at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) --- End of inner exception stack trace --- at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Delegate.DynamicInvokeImpl(Object[] args) at CounterStrikeSharp.API.Core.FunctionReference.b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

Are you using lastest version?

**Comment by gha241** [comment]
Yes

**Comment by schwarper** [comment]
@gha241 
Can you show me your config?

**Comment by SkyJust4Fun** [comment]
Its weird, the same happens to me from 0.0.5 to the latest version in 1 server but works correctly in another running server using 0.0.5 maybe its conflicting with something?

The both server running v260 csharp

Tags plugins (This one and VIP_Tags)

**Comment by SkyJust4Fun** [comment]
Also !toggletags are only toggling chat tag and not scoreboard one.

**Comment by schwarper** [comment]
@SkyJust4Fun 
Can you update the files and try again? If the error persists, please reopen the ticket.

**Comment by SkyJust4Fun** [comment]
Not atm sorry will try later
